name: Envio Automatizado de Reporte Mensual Finanzas

on:
  schedule:
    # Corre el día 28, 29, 30 y 31 de cada mes a las 23:00 UTC.
    - cron: '0 23 28-31 * *'
  workflow_dispatch: # Te permite picar el botón en GitHub para probarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # <--- Corregido aquí para evitar el error de sintaxis

      - name: Instalar Dependencias
        run: |
          pip install pandas gspread oauth2client fpdf2

      - name: Ejecutar Script de Reporte
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          CORREO_REMITENTE: ${{ secrets.CORREO_REMITENTE }}
          CORREO_DESTINATARIO: ${{ secrets.CORREO_DESTINATARIO }}
          CORREO_PASSWORD: ${{ secrets.CORREO_PASSWORD }}
        run: |
          # Quitamos temporalmente el candado de fecha para que la prueba de hoy funcione
          python reporte_mensual.py
